industries = ['Advertising', 'Agriculture and Farming', 'Life Sciences', 'Clothing and Apparel',
              'Commerce and Shopping', 'Community and Lifestyle', 'Consumer Electronics', 'Consumer Goods',
              'Content and Publishing', 'Design', 'Education', 'Energy', 'Environment and Sustainability', 'Events',
              'Financial Services', 'Food and Beverage', 'Gaming', 'Government and Military', 'Computer Hardware',
              'Health Care', 'HumanResources', 'Software', 'Legal', 'Logistics', 'Manufacturing', 'Data and Analytics',
              'Media and Entertainment', 'Messaging and Telecommunications', 'Music and Audio', 'Natural Resources',
              'Navigation and Mapping', 'Payments', 'Privacy and Security', 'Professional Services',
              'Real Estate and Construction', 'Sales and Marketing', 'Sports', 'Transportation', 'Travel and Tourism',
              'Video']

technologies = ['Artificial Intelligence', 'Biotechnology', 'Hardware', 'Science and Engineering', 'Software',
                'Sustainability', 'BlockChain', 'AR and VR']

columns = ['num_funding_rounds',
    'last_equity_funding_total',
    'employeeCount',
    'Advertising',
    'Agriculture and Farming',
    'Clothing and Apparel',
    'Commerce and Shopping',
    'Community and Lifestyle',
    'Computer Hardware',
    'Consumer Electronics',
    'Consumer Goods',
    'Content and Publishing',
    'Data and Analytics',
    'Design',
    'Education',
    'Energy',
    'Environment and Sustainability',
    'Events',
    'Financial Services',
    'Food and Beverage',
    'Gaming',
    'Government and Military',
    'Health Care',
    'HumanResources',
    'Legal',
    'Life Sciences',
    'Logistics',
    'Manufacturing',
    'Media and Entertainment',
    'Messaging and Telecommunications',
    'Music and Audio',
    'Natural Resources',
    'Navigation and Mapping',
    'Payments',
    'Privacy and Security',
    'Professional Services',
    'Real Estate and Construction',
    'Sales and Marketing',
    'Software_x',
    'Sports',
    'Transportation',
    'Travel and Tourism',
    'Video',
    'AR and VR',
    'Artificial Intelligence',
    'Biotechnology',
    'BlockChain',
    'Hardware',
    'Science and Engineering',
    'Software_y',
    'Sustainability',
    'Round 1',
    'Round 2',
    'Round 3',
    'Round 4',
    'Round 5',
    'CN',
    'US',
    'VN',
    'CO',
    'CA',
    'DK',
    'JP',
    'SE',
    'BE',
    'NL',
    'IT',
    'AU',
    'OTHERS',
    'IL',
    'ES',
    'DE',
    'IN',
    'CH',
    'AR',
    'GB',
    'KR',
    'BR',
    'PT',
    'EG',
    'PL',
    'FR',
    'HK',
    'TW',
    'NO',
    'RO',
    'BD',
    'RU',
    'ZA',
    'MY',
    'IE',
    'MX',
    'NG',
    'AE',
    'EE',
    'CL',
    'PK',
    'SG',
    'HU',
    'CZ',
    'UA',
    'LU',
    'CY',
    'ID',
    'KE',
    'FI',
    'AT',
    'UG',
    'TR',
    'NZ',
    'TH',
    'GH',
    'SA',
    'LT',
    'PH',
    'LV',
    'BG',
    'GR',
    'seed',
    'pre_seed',
    'private_equity',
    'series_a',
    'angel',
    'equity_crowdfunding',
    'series_b',
    'series_c',
    'post_ipo_equity',
    'series_d',
    'series_e',
    'series_f',
    'series_g',
    'series_h',
    'days_between_dates',
    'Target'
]
