industries = ['Advertising', 'Agriculture and Farming', 'Life Sciences', 'Clothing and Apparel',
              'Commerce and Shopping', 'Community and Lifestyle', 'Consumer Electronics', 'Consumer Goods',
              'Content and Publishing', 'Design', 'Education', 'Energy', 'Environment and Sustainability', 'Events',
              'Financial Services', 'Food and Beverage', 'Gaming', 'Government and Military', 'Computer Hardware',
              'Health Care', 'HumanResources', 'Software', 'Legal', 'Logistics', 'Manufacturing', 'Data and Analytics',
              'Media and Entertainment', 'Messaging and Telecommunications', 'Music and Audio', 'Natural Resources',
              'Navigation and Mapping', 'Payments', 'Privacy and Security', 'Professional Services',
              'Real Estate and Construction', 'Sales and Marketing', 'Sports', 'Transportation', 'Travel and Tourism',
              'Video']

technologies = ['Artificial Intelligence', 'Biotechnology', 'Hardware', 'Science and Engineering', 'Software',
                'Sustainability', 'BlockChain', 'AR and VR']

new_codes = {'Other': 'OTHERS', 'China': 'CN', 'United States': 'US', 'Viet Nam': 'VN', 'Colombia': 'CO', 'Canada': 'CA',
             'Denmark': 'DK', 'Japan': 'JP', 'Sweden': 'SE', 'Belgium': 'BE', 'Netherlands': 'NL', 'Italy': 'IT',
             'Australia': 'AU', 'Israel': 'IL', 'Spain': 'ES', 'Germany': 'DE', 'India': 'IN', 'Switzerland': 'CH',
             'Argentina': 'AR', 'United Kingdom': 'GB', 'Korea, Republic of': 'KR', 'Brazil': 'BR', 'Portugal': 'PT',
             'Egypt': 'EG', 'Poland': 'PL', 'France': 'FR', 'Hong Kong': 'HK', 'Taiwan': 'TW', 'Norway': 'NO',
             'Romania': 'RO', 'Bangladesh': 'BD', 'Russian Federation': 'RU', 'South Africa': 'ZA', 'Malaysia': 'MY',
             'Ireland': 'IE', 'Mexico': 'MX', 'Nigeria': 'NG', 'United Arab Emirates': 'AE', 'Estonia': 'EE',
             'Chile': 'CL', 'Pakistan': 'PK', 'Singapore': 'SG', 'Hungary': 'HU', 'Czech Republic': 'CZ',
             'Ukraine': 'UA', 'Luxembourg': 'LU', 'Cyprus': 'CY', 'Indonesia': 'ID', 'Kenya': 'KE', 'Finland': 'FI',
             'Austria': 'AT', 'Uganda': 'UG', 'Turkey': 'TR', 'New Zealand': 'NZ', 'Thailand': 'TH', 'Ghana': 'GH',
             'Saudi Arabia': 'SA', 'Lithuania': 'LT', 'Philippines': 'PH', 'Latvia': 'LV', 'Bulgaria': 'BG', 'Greece': 'GR'}

regions = {
    'CN': 'Asia',
    'US': 'United States',
    'VN': 'Asia',
    'CO': 'South America',
    'CA': 'North America',
    'DK': 'Europe',
    'JP': 'Asia',
    'SE': 'Europe',
    'BE': 'Europe',
    'NL': 'Europe',
    'IT': 'Europe',
    'AU': 'Oceania',
    'MU': 'Africa',
    'IL': 'Middle East',
    'ES': 'Europe',
    'DE': 'Europe',
    'IN': 'Asia',
    'CH': 'Europe',
    'AR': 'South America',
    'GB': 'Europe',
    'KR': 'Asia',
    'BR': 'South America',
    'KW': 'Middle East',
    'BJ': 'Africa',
    'PT': 'Europe',
    'EG': 'Africa',
    'PL': 'Europe',
    'FR': 'Europe',
    'HK': 'Asia',
    'PA': 'Central America',
    'TW': 'Asia',
    'PS': 'Middle East',
    'NO': 'Europe',
    'RO': 'Europe',
    'BD': 'Asia',
    'RU': 'Europe',
    'ZA': 'Africa',
    'MY': 'Asia',
    'IE': 'Europe',
    'MX': 'Central America',
    'NG': 'Africa',
    'AE': 'Middle East',
    'EE': 'Europe',
    'CL': 'South America',
    'PK': 'Asia',
    'RS': 'Europe',
    'SG': 'Asia',
    'HU': 'Europe',
    'CZ': 'Europe',
    'AZ': 'Asia',
    'CD': 'Africa',
    'UA': 'Europe',
    'GI': 'Europe',
    'BM': 'North America',
    'LU': 'Europe',
    'CY': 'Asia',
    'ID': 'Asia',
    'SN': 'Africa',
    'RW': 'Africa',
    'KE': 'Africa',
    'FI': 'Europe',
    'AT': 'Europe',
    'UG': 'Africa',
    'TR': 'Asia',
    'MT': 'Europe',
    'IS': 'Europe',
    'PE': 'South America',
    'CR': 'Central America',
    'TN': 'Africa',
    'NZ': 'Oceania',
    'ET': 'Africa',
    'TH': 'Asia',
    'IR': 'Middle East',
    'TT': 'South America',
    'KY': 'Central America',
    'MG': 'Africa',
    'GH': 'Africa',
    'PR': 'Central America',
    'SA': 'Middle East',
    'HR': 'Europe',
    'TZ': 'Africa',
    'LK': 'Asia',
    'NI': 'Central America',
    'ML': 'Africa',
    'JM': 'Central America',
    'LT': 'Europe',
    'PH': 'Asia',
    'ZM': 'Africa',
    'LV': 'Europe',
    'UY': 'South America',
    'JO': 'Middle East',
    'BG': 'Europe',
    'PG': 'Oceania',
    'MM': 'Asia',
    'GT': 'Central America',
    'GR': 'Europe',
    'SK': 'Europe',
    'IQ': 'Middle East',
    'SL': 'Africa',
    'SI': 'Europe',
    'DZ': 'Africa',
    'LI': 'Europe',
    'BY': 'Europe',
    'IM': 'Europe',
    'GE': 'Asia',
    'MK': 'Europe',
    'SV': 'Central America',
    'IO': 'Asia',
    'SC': 'Africa',
    'MN': 'Asia',
    'CI': 'Africa',
    'MA': 'Africa',
    'PY': 'South America',
    'QA': 'Middle East',
    'LB': 'Middle East',
    'OM': 'Middle East',
    'MW': 'Africa',
    'GN': 'Africa',
    'AM': 'Asia',
    'BH': 'Middle East',
    'BA': 'Europe',
    'CM': 'Africa',
    'KZ': 'Asia',
    'BB': 'Central America',
    'NP': 'Asia',
    'DO': 'Central America',
    'BS': 'Central America',
    'KH': 'Asia',
    'EC': 'South America',
    'TG': 'Africa',
    'BT': 'Asia',
    'AS': 'Oceania',
    'ZW': 'Africa',
    'GM': 'Africa',
    'JE': 'Europe',
    'YE': 'Middle East',
    'UZ': 'Asia',
    'AI': 'Central America',
    'HN': 'Central America',
    'BZ': 'Central America',
    'MZ': 'Africa',
    'BO': 'South America',
    'KN': 'Central America',
    'AO': 'Africa',
    'GG': 'Europe',
    'ME': 'Europe',
    'BN': 'Asia',
    'GY': 'South America',
    'SD': 'Africa',
    'VG': 'Central America',
    'DJ': 'Africa',
    'LC': 'Central America',
    'CU': 'Central America',
    'LS': 'Africa',
    'MD': 'Europe',
    'AL': 'Europe',
    'AF': 'Asia',
    'MV': 'Asia',
    'BW': 'Africa',
    'RE': 'Central America',
    'LA': 'Asia',
    'LY': 'Africa'
}
